spring:
  datasource:
    url: jdbc:h2:mem:servicedb;MODE=MYSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: update